# Simulation using Python, Lab 2, Part B

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import random

**Exploration**
Randomly explore the search space and report the best solution found for the Rosenbrock Function

In [2]:
#Let's define the 2-D Rosenbrock function
def Rosenbrock(x1, x2):
  return ((1-x1)**2 + 100*(x2 -x1**2)**2)


In [3]:
  N =10**4 ## number of random points
  D = 2 ##Dimension 
  lb = -4 ## lower bound
  ub = 4  ## upper bound
  X1=[]
  X2=[]
  Y=[]

  #randomly generate N points. We are using Numpy's random package here.
  X1 = np.random.uniform(lb, ub, N)
  X2 = np.random.uniform(lb, ub, N)

  #Evaluate the function
  for i in range(N):
      Y.append(Rosenbrock(X1[i], X2[i]))
      
  #display Results
  print("\n \n for n=",N)
  print('\n Monte Carlo Simulation Optimisation\n')
  print( 'Best decision variable : ', X1[np.argmin(Y)], X2[np.argmin(Y)])
  print('Best objective    : ', min(Y))

  X_optimum = [1,1] #Known from theory
  print("Known Optimal decision variables:",X_optimum)
  print("Known Optimal objective =",Rosenbrock(X_optimum[0], X_optimum[1]))


 
 for n= 10000

 Monte Carlo Simulation Optimisation

Best decision variable :  0.9872562291847444 0.9778507735120412
Best objective    :  0.0011710450471204721
Known Optimal decision variables: [1, 1]
Known Optimal objective = 0


 for n= 10000

 Monte Carlo Simulation Optimisation

Best decision variable :  0.9599108034981869 0.9386895084480278


Best objective    :  0.03140051957458506


Known Optimal decision variables: [1, 1]


Known Optimal objective = 0

'Optimise' above model for different values of N.  Observe how just randomly searching the soultion space yields pretty good results!

In [4]:
m =[10,100,1000,10**4,10**5] ## number of random points
D = 2 ##Dimension 
lb = -4 ## lower bound
ub = 4  ## upper bound
print('\n Monte Carlo Simulation Optimisation\n')
for N in m:
  X1=[]
  X2=[]
  Y=[]

  #randomly generate N points. We are using Numpy's random package here.
  X1 = np.random.uniform(lb, ub, N)
  X2 = np.random.uniform(lb, ub, N)

  #Evaluate the function
  for i in range(N):
      Y.append(Rosenbrock(X1[i], X2[i]))
      
  #display Results
  print("\n \n for n=",N)
  print( '\n Best decision variable : ', X1[np.argmin(Y)], X2[np.argmin(Y)])
  print('\n Best objective    : ', min(Y))

  X_optimum = [1,1] #Known from theory
  print("\n Known Optimal decision variables:",X_optimum)
  print("\n Known Optimal objective =",Rosenbrock(X_optimum[0], X_optimum[1]))


 Monte Carlo Simulation Optimisation


 
 for n= 10

 Best decision variable :  -0.10795006105364635 -0.08824194261571972

 Best objective    :  2.225457602911157

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 100

 Best decision variable :  1.028488872616042 1.1845308043893583

 Best objective    :  1.6071509606962098

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 1000

 Best decision variable :  0.5908859075671815 0.38238031936241246

 Best objective    :  0.2778253036524049

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 10000

 Best decision variable :  1.00439878792666 1.0058653372674078

 Best objective    :  0.0008905364608432782

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 100000

 Best decision variable :  0.9913160145424893 0.9794092241947565

 Best objective    :  0.0011632348073236688

 Known Optimal decision variables: [1, 1]

Monte Carlo Simulation Optimisation


 
 for n= 10

 Best decision variable :  -1.2737090574661192 2.6366757662186906

 Best objective    :  108.0585199446232

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 100

 Best decision variable :  1.0275424840145275 1.0005445652715945

 Best objective    :  0.3065564310131112

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 1000

 Best decision variable :  0.639009919806492 0.39759342191945723

 Best objective    :  0.1418491472303004

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 10000

 Best decision variable :  0.9806015062843052 0.9581625735469528

 Best objective    :  0.0015437131776049465

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 
 for n= 100000

 Best decision variable :  0.9502376713534062 0.9060884310918533

 Best objective    :  0.003460240169492247

 Known Optimal decision variables: [1, 1]

 Known Optimal objective = 0

 as we increase n we tends to known optimal solution but some times we can get best solution in small value of n also if random varible generate sample near to our optimal solution but it chance is less compare to when we take n large

##To Do

You can find some single objective unconstrained test functions at [Wiki page](https://en.wikipedia.org/wiki/Test_functions_for_optimization)

1. Through simulation, estimate the best solution of any one of the function: Beale or Goldstein-Price or Booth (need to minimize)

2. 'Minimize' either Himmelblau's function OR Cross-in-Tray function. These functions have 4 alternate solutions.  Do 20 sets of 'simulation-optimisation' runs, with N ~= 200000. Compute the number of times we are close to a particular known solution.

##beale function

In [5]:
def beale(x,y):
  return (1.5-x+x*y)**2+(2.25-x+x*(y**2))**2 + (2.625-x+x*(y**3))**2

In [6]:
m =[10,100,1000,10**4] ## number of random points
D = 2 ##Dimension 
lb = -4.5 ## lower bound
ub = 4.5  ## upper bound
print('\n Monte Carlo Simulation Optimisation\n')
for N in m:
  X1=[]
  X2=[]
  Y=[]

  #randomly generate N points. We are using Numpy's random package here.
  X1 = np.random.uniform(lb, ub, N)
  X2 = np.random.uniform(lb, ub, N)

  #Evaluate the function
  for i in range(N):
      Y.append(beale(X1[i], X2[i]))
      
  #display Results
  print("\n \n for n=",N)
  print( '\n Best decision variable : ', X1[np.argmin(Y)], X2[np.argmin(Y)])
  print('\n Best objective    : ', min(Y))
  print('\n known objective value is',0)
  print('\n known decision variable','{3,0.5}')



 Monte Carlo Simulation Optimisation


 
 for n= 10

 Best decision variable :  2.6625385469786735 0.7839108412085967

 Best objective    :  3.9024794803673784

 known objective value is 0

 known decision variable {3,0.5}

 
 for n= 100

 Best decision variable :  2.2966975212486442 0.2527921527556636

 Best objective    :  0.1902380445145216

 known objective value is 0

 known decision variable {3,0.5}

 
 for n= 1000

 Best decision variable :  3.208432932700447 0.5342436026705872

 Best objective    :  0.01072937362114674

 known objective value is 0

 known decision variable {3,0.5}

 
 for n= 10000

 Best decision variable :  3.172067709212012 0.5420089565826345

 Best objective    :  0.004088752356676624

 known objective value is 0

 known decision variable {3,0.5}



 Monte Carlo Simulation Optimisation


 
 for n= 10

 Best decision variable :  1.5849300809011329 0.803056632359958

 Best objective    :  7.720538429926544

 known objective value is 0

 known decision variable {3,0.5}

 
 for n= 100

 Best decision variable :  2.7013861369558 0.15911218448132392

 Best objective    :  0.7462857389347811

 known objective value is 0

 known decision variable {3,0.5}

 
 for n= 1000

 Best decision variable :  2.976057151997181 0.5087536377468327

 Best objective    :  0.005069895038922639

 known objective value is 0

 known decision variable {3,0.5}

 
 for n= 10000

 Best decision variable :  3.2219283519982964 0.5612907718473732

 Best objective    :  0.010083366166460595

 known objective value is 0

 known decision variable {3,0.5}

##goldstein function

In [7]:
def goldstein(x,y):
  return (1+((x+y+1)**2)*(19-14*x+3*(x**2)-14*y+6*x*y+3*(y**2)))*(30+((2*x-3*y)**2)*(18-32*x+12*x**2+48*y-36*x*y+27*(y**2)))

In [8]:
m =[10,100,1000,10**4,10**5] ## number of random points
D = 2 ##Dimension 
lb = -2 ## lower bound
ub = 2  ## upper bound
print('\n Monte Carlo Simulation Optimisation\n')
for N in m:
  X1=[]
  X2=[]
  Y=[]

  #randomly generate N points. We are using Numpy's random package here.
  X1 = np.random.uniform(lb, ub, N)
  X2 = np.random.uniform(lb, ub, N)

  #Evaluate the function
  for i in range(N):
      Y.append(goldstein(X1[i], X2[i]))
      
  #display Results
  print("\n \n for n=",N)
  print( '\n Best decision variable : ', X1[np.argmin(Y)], X2[np.argmin(Y)])
  print('\n Best objective    : ', min(Y))
  print('\n known objective value is',3)
  print('\n known decision variable','{0,-1}')


 Monte Carlo Simulation Optimisation


 
 for n= 10

 Best decision variable :  -0.23844311342682145 -1.0682824368835129

 Best objective    :  26.340198515831414

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 100

 Best decision variable :  -0.3439268339744266 -0.7669742081226443

 Best objective    :  44.10299230941397

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 1000

 Best decision variable :  0.17890248748948911 -0.8442383130545301

 Best objective    :  14.712489417123141

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 10000

 Best decision variable :  -0.006868379383383694 -0.9998166739265226

 Best objective    :  3.012146022383102

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 100000

 Best decision variable :  -0.004181120721937326 -0.9998752558108337

 Best objective    :  3.004517099360525

 known objective value is 3

 known decision variable {0,-1}



 Monte Carlo Simulation Optimisation


 
 for n= 10

 Best decision variable :  -0.2558739801372756 -0.955547485640615

 Best objective    :  36.8243468086567

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 100

 Best decision variable :  -0.08175794089164867 -1.101897952845031

 Best objective    :  8.866184105875735

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 1000

 Best decision variable :  -0.025921305109020132 -1.0089822610845318

 Best objective    :  3.1571259498958595

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 10000

 Best decision variable :  -0.03561473791132519 -1.0133450488002942

 Best objective    :  3.3034549298909024

 known objective value is 3

 known decision variable {0,-1}

 
 for n= 100000

 Best decision variable :  -0.0009918398005424045 -1.000365093347877

 Best objective    :  3.000227407834769

 known objective value is 3

 known decision variable {0,-1}

##himmelblau function 

In [9]:
def himmelblau(x,y):
  return (x**2 + y -11)**2 +(x+y**2-7)**2

In [10]:
N=2*(10**5) ## number of random points
D = 2 ##Dimension 
lb = -5 ## lower bound
ub = 5  ## upper bound
count1=0
count2=0
count3=0
count4=0
print('\n Monte Carlo Simulation Optimisation\n')
for i in range(20):
  X1=[]
  X2=[]
  Y=[]

  #randomly generate N points. We are using Numpy's random package here.
  X1 = np.random.uniform(lb, ub, N)
  X2 = np.random.uniform(lb, ub, N)

  #Evaluate the function
  for j in range(N):
      Y.append(himmelblau(X1[j], X2[j]))    
  #display Results
  print('\n \n \n set no=',i)
  print( '\n Best decision variable : ', X1[np.argmin(Y)], X2[np.argmin(Y)])
  print('\n Best objective    : ', min(Y))
  print('\n known objective value is',0)
  print('\n known decision variable','{3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}')


 Monte Carlo Simulation Optimisation


 
 
 set no= 0

 Best decision variable :  -3.776556378923308 -3.2808347218566136

 Best objective    :  0.0005014275470397989

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 1

 Best decision variable :  3.5871340739567827 -1.8394366076828952

 Best objective    :  0.0016500578733215508

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 2

 Best decision variable :  3.0027936308140877 2.0036161233739396

 Best objective    :  0.000713871651670193

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 3

 Best decision variable :  3.584193666298969 -1.8466463941815023

 Best objective    :  3.256996461901264e-05

 known objective value is 0

 known decision variable {3.0,2.0},


 Monte Carlo Simulation Optimisation


 
 
 set no= 0

 Best decision variable :  3.0085981921624896 1.998994603673978

 Best objective    :  0.002587155689656138

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 1

 Best decision variable :  -2.8104428929927563 3.12943659166581

 Best objective    :  0.0010768162995391942

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 2

 Best decision variable :  -3.777939660330185 -3.282350593934283

 Best objective    :  0.00010760528808577842

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 3

 Best decision variable :  -3.784906029186381 -3.285194363043098

 Best objective    :  0.0016833437000042311

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 4

 Best decision variable :  2.9994304609893945 2.001758955026876

 Best objective    :  4.4601626806806195e-05

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 5

 Best decision variable :  -3.775684367416814 -3.281842594490133

 Best objective    :  0.0007055834128319763

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 6

 Best decision variable :  3.585838284713608 -1.8585291477876718

 Best objective    :  0.0015975970157776406

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 7

 Best decision variable :  3.5850823415342816 -1.8464017247800824

 Best objective    :  7.383446192236127e-05

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 8

 Best decision variable :  3.5801972087935106 -1.8439879808335622

 Best objective    :  0.0010658628690704375

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 9

 Best decision variable :  3.581175900513209 -1.8520712395986374

 Best objective    :  0.0008712660786131205

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 10

 Best decision variable :  -3.7795915184536764 -3.279038634925363

 Best objective    :  0.0007954489008700488

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 11

 Best decision variable :  2.998824797284694 1.9941678977577642

 Best objective    :  0.0007647055514006203

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 12

 Best decision variable :  -2.8038962181874005 3.1390892301189126

 Best objective    :  0.00249935023004188

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 13

 Best decision variable :  2.998711604833815 2.008282566206071

 Best objective    :  0.0010185848869785814

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 14

 Best decision variable :  3.588117723136243 -1.8455947497135816

 Best objective    :  0.0008727162708102448

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 15

 Best decision variable :  2.999875919477244 2.008693240468876

 Best objective    :  0.0012689706783861967

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 16

 Best decision variable :  2.9951798527151574 2.0049262242605694

 Best objective    :  0.0007969080477820236

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 17

 Best decision variable :  3.004440039029273 2.0088098913497294

 Best objective    :  0.002838745944070085

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 18

 Best decision variable :  -3.7759963392476004 -3.279212018172056

 Best objective    :  0.0009619176693879351

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

 
 
 set no= 19

 Best decision variable :  -3.78398203465136 -3.286342301482973

 Best objective    :  0.001293448831497137

 known objective value is 0

 known decision variable {3.0,2.0},{-2.805118,3.131312},{-3.779310,-3.283186},{3.584428,-1.848126}

In [11]:
N=2*(10**5) ## number of random points
D = 2 ##Dimension 
lb = -5 ## lower bound
ub = 5  ## upper bound
count1=0
count2=0
count3=0
count4=0
print('\n Monte Carlo Simulation Optimisation\n')
for i in range(20):
  X1=[]
  X2=[]
  Y=[]
  #randomly generate N points. We are using Numpy's random package here.
  X1 = np.random.uniform(lb, ub, N)
  X2 = np.random.uniform(lb, ub, N)

  #Evaluate the function
  for j in range(N):
      Y.append(himmelblau(X1[j], X2[j]))    
  #display Results
  if 2.98<= X1[np.argmin(Y)] <=3.01 and 1.98<= X2[np.argmin(Y)] <=2.019 and -0.19<=min(Y)<=0.19:
    count1+=1
  elif -2.82<= X1[np.argmin(Y)] <=-2.79 and 3.12<= X2[np.argmin(Y)] <=3.14 and -0.19<=min(Y)<=0.19:
    count2+=1
  elif -3.79<= X1[np.argmin(Y)] <=-3.76 and -3.29<= X2[np.argmin(Y)] <=-3.27 and -0.19<=min(Y)<=0.19:
    count3+=1
  elif 3.57<= X1[np.argmin(Y)] <=3.60 and -1.87<= X2[np.argmin(Y)] <=-1.83 and -0.19<=min(Y)<=0.19:
    count4+=1
  else:
    print(X1[np.argmin(Y)],X2[np.argmin(Y)])
print('\n number of times decision variable close to known solution (3.0,2.0)',count1)
print('\n number of times decision variable close to known solution (-2.805118,3.131312)',count2)
print('\n number of times decision variable close to known solution (-3.779310,-3.283186)',count3)
print('\n number of times decision variable close to known solution (3.584428,-1.848126)',count4)


 Monte Carlo Simulation Optimisation


 number of times decision variable close to known solution (3.0,2.0) 7

 number of times decision variable close to known solution (-2.805118,3.131312) 3

 number of times decision variable close to known solution (-3.779310,-3.283186) 5

 number of times decision variable close to known solution (3.584428,-1.848126) 5



 Monte Carlo Simulation Optimisation


 number of times decision variable close to (3.0,2.0) 7

 number of times decision variable close to (-2.805118,3.131312) 3

 number of times decision variable close to (-3.779310,-3.283186) 2

 number of times decision variable close to (3.584428,-1.848126) 8

#Optional To Do

Consider flight IEX 306 that flies daily from Mumbai to Chennai. Flight has 100 seats.  Price of a ticket is on an average Rs. 6000.  There is 10% chance that a sold seat will remain vacant (i.e. passenger doesn’t show up). Airline refunds 50% of the price of ticket to that passenger for such last minute cancellations.  
Daily demand for seats is Poisson distributed with mean 120.   
Now, the airline can decide to sell $x$ tickets, where $x4 can be more or less than the capacity of plane.  
If the airline overbooks, then it pays an average of Rs.10000 for any passenger who is ‘bumped’ (i.e. denied seat in plane). 

What is the value of $x$ (the number of tickets to sell) that maximizes the expected profit? (Hint: You can run the model for different values of $x$ from say 90 to 150 and choose the $x$ which gives the maximum profit)

when we does not cosider penalty cost(when demand is greater than sell in some model we consider penalty cost)

In [12]:
selling_price=6000
refund_cancellation=3000
seat_capacity=100
bumped_charge=10000
x=[90+i for i in range(0,61)]
def profit(y):
  return selling_price*y-max(0,show-seat_capacity)*bumped_charge-max(0,y-show)*refund_cancellation
p=[]
for i in x:
  for j in range(10**5):
    prof=[]
    show=np.random.binomial(i,0.9)
    prof.append(profit(i))
  p.append(np.mean(prof))
for i in range(len(p)):
  if p[i]==max(p):
    print('number of ticket to sell when we does not consider penalty cost',90+i)

number of ticket to sell when we does not consider penalty cost 118


when we consider penalty cost as 3000
(when demand is greater than sell in some model we consider penalty cost)

number of ticket to sell when we does not consider penalty cost 123

number of ticket to sell when we consider penalty cost as 3000 117

number of ticket to sell when we consider penalty cost as 6000 119

In [13]:
selling_price=6000
refund_cancellation=3000
seat_capacity=100
bumped_charge=10000
x=[90+i for i in range(0,61)]
def profit(y):
  return selling_price*y-max(0,show-seat_capacity)*bumped_charge-max(0,y-show)*refund_cancellation-max(0,demand-y)*3000
p=[]
for i in x:
  for j in range(10**5):
    prof=[]
    demand=np.random.poisson(120)
    show=np.random.binomial(i,0.9)
    prof.append(profit(i))
  p.append(np.mean(prof))
for i in range(len(p)):
  if p[i]==max(p):
    print('number of ticket to sell when we consider penalty cost as 3000',90+i)


number of ticket to sell when we consider penalty cost as 3000 115


when we consider penalty cost as 6000 (when demand is greater than sell in some model we consider penalty cost)

In [14]:
selling_price=6000
refund_cancellation=3000
seat_capacity=100
bumped_charge=10000
x=[90+i for i in range(0,61)]
def profit(y):
  return selling_price*y-max(0,show-seat_capacity)*bumped_charge-max(0,y-show)*refund_cancellation-max(0,demand-y)*6000
p=[]
for i in x:
  for j in range(10**5):
    prof=[]
    demand=np.random.poisson(120)
    show=np.random.binomial(i,0.9)
    prof.append(profit(i))
  p.append(np.mean(prof))
for i in range(len(p)):
  if p[i]==max(p):
    print('number of ticket to sell when we consider penalty cost as 6000',90+i)


number of ticket to sell when we consider penalty cost as 6000 116


number of ticket to sell when we consider penalty cost as 6000 117

